environment:
  profile: 开发环境
  position: 个人笔记本

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyTestDb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      one:
        initial-size: 8
        min-idle: 1
        max-active: 20
        max-wait: 60000
      two:
        initial-size: 8
        min-idle: 1
        max-active: 20
        max-wait: 60000

  redis:
    host: localhost
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-wait: 30000
        max-active: 10
        max-idle: 5
        min-idle: 0

